//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSW2_Controller.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sprache {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sprache() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSW2_Controller.Properties.Sprache", typeof(Sprache).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als Wert für den Zeitfaktor kannst du nun  ähnelt.
        /// </summary>
        internal static string Als_Wert_für_den_Zeitfaktor_kannst_du_nun {
            get {
                return ResourceManager.GetString("Als Wert für den Zeitfaktor kannst du nun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf welcher Zahl bist du gelandet? ähnelt.
        /// </summary>
        internal static string Auf_welcher_Zahl_bist_du_gelandet {
            get {
                return ResourceManager.GetString("Auf welcher Zahl bist du gelandet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bremse ist ähnelt.
        /// </summary>
        internal static string Bremse_ist {
            get {
                return ResourceManager.GetString("Bremse ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bremsindikator leer! Standard laden? ähnelt.
        /// </summary>
        internal static string Bremsindikator_Leer__Standard_Laden {
            get {
                return ResourceManager.GetString("Bremsindikator_Leer__Standard_Laden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drücke nochmal auf OK, wechsel innerhalb von 7 Sekunden zum TSW und warte ähnelt.
        /// </summary>
        internal static string Druecke_nochmal_auf_OK_wechsel_innerhalb_von_7_Sekunden_zum_TSW_und_warte {
            get {
                return ResourceManager.GetString("Druecke nochmal auf OK wechsel innerhalb von 7 Sekunden zum TSW und warte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast die neueste Version ähnelt.
        /// </summary>
        internal static string Du_hast_die_neueste_Version {
            get {
                return ResourceManager.GetString("Du hast die neueste Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast noch keinen Startwert eingetragen! ähnelt.
        /// </summary>
        internal static string Du_hast_noch_keinen_Startwert_eingetragen {
            get {
                return ResourceManager.GetString("Du_hast_noch_keinen_Startwert_eingetragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Einträge gelöscht! ähnelt.
        /// </summary>
        internal static string Eintraege_geloescht {
            get {
                return ResourceManager.GetString("Eintraege_geloescht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  eintragen ähnelt.
        /// </summary>
        internal static string eintragen {
            get {
                return ResourceManager.GetString("eintragen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot; entfernen? ähnelt.
        /// </summary>
        internal static string entfernen {
            get {
                return ResourceManager.GetString("entfernen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ersetzt ähnelt.
        /// </summary>
        internal static string Ersetzt {
            get {
                return ResourceManager.GetString("Ersetzt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erstellt ähnelt.
        /// </summary>
        internal static string Erstellt {
            get {
                return ResourceManager.GetString("Erstellt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string Fehler {
            get {
                return ResourceManager.GetString("Fehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler bei Auflösung! ähnelt.
        /// </summary>
        internal static string Fehler_bei_Aufloesung {
            get {
                return ResourceManager.GetString("Fehler_bei_Aufloesung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Textindikator! ähnelt.
        /// </summary>
        internal static string Fehler_beim_Textindikator {
            get {
                return ResourceManager.GetString("Fehler_beim_Textindikator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig! ähnelt.
        /// </summary>
        internal static string Fertig {
            get {
                return ResourceManager.GetString("Fertig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzugefügt ähnelt.
        /// </summary>
        internal static string Hinzugefuegt {
            get {
                return ResourceManager.GetString("Hinzugefuegt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hmm, da hast du wohl etwas falsch gemacht. Die Startzahl sollte größer als die Endzahl sein. ähnelt.
        /// </summary>
        internal static string Hmm_da_hast_du_wohl_etwas_falsch_gemacht_Die_Startzahl_sollte_groeßer_als_die_Endzahl_sein {
            get {
                return ResourceManager.GetString("Hmm da hast du wohl etwas falsch gemacht Die Startzahl sollte groeßer als die End" +
                        "zahl sein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hmm, da hat etwas nicht funktioniert. Versuche es doch nochmal. ähnelt.
        /// </summary>
        internal static string Hmm_da_hat_etwas_nicht_funktioniert_Versuche_es_doch_nochmal {
            get {
                return ResourceManager.GetString("Hmm da hat etwas nicht funktioniert Versuche es doch nochmal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ist verfügbar! Möchtest du aktualisieren? ähnelt.
        /// </summary>
        internal static string ist_verfuegbar_Moechtest_du_aktualisieren {
            get {
                return ResourceManager.GetString("ist verfuegbar Moechtest du aktualisieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Joystick angeschlossen! ähnelt.
        /// </summary>
        internal static string Kein_Joystick_angeschlossen {
            get {
                return ResourceManager.GetString("Kein Joystick angeschlossen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Nummer erkannt. Kann es sein, dass du beim Maximum gelandet bist? ähnelt.
        /// </summary>
        internal static string Keine_Nummer_erkannt_Kann_es_sein_dass_du_beim_Maximum_gelandet_bist {
            get {
                return ResourceManager.GetString("Keine Nummer erkannt Kann es sein dass du beim Maximum gelandet bist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kombihebel_Bremsindikator leer! Standard laden? ähnelt.
        /// </summary>
        internal static string Kombihebel_Bremsindikator_Leer__Standard_Laden {
            get {
                return ResourceManager.GetString("Kombihebel_Bremsindikator_Leer__Standard_Laden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kombihebel_Schubindikator leer! Standard laden? ähnelt.
        /// </summary>
        internal static string Kombihebel_Schubindikator_Leer__Standard_Laden {
            get {
                return ResourceManager.GetString("Kombihebel_Schubindikator_Leer__Standard_Laden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JoyName ähnelt.
        /// </summary>
        internal static string lblT1_JoyName {
            get {
                return ResourceManager.GetString("lblT1_JoyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die KnopfNr. ähnelt.
        /// </summary>
        internal static string lblT1_KnopfNr {
            get {
                return ResourceManager.GetString("lblT1_KnopfNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot; löschen? ähnelt.
        /// </summary>
        internal static string loeschen {
            get {
                return ResourceManager.GetString("loeschen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du &quot; ähnelt.
        /// </summary>
        internal static string Moechtest_du {
            get {
                return ResourceManager.GetString("Moechtest_du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nr: ähnelt.
        /// </summary>
        internal static string Nr {
            get {
                return ResourceManager.GetString("Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK, dann stelle den Regler nochmal auf  ähnelt.
        /// </summary>
        internal static string OK_dann_stelle_den_Regler_nochmal_auf {
            get {
                return ResourceManager.GetString("OK dann stelle den Regler nochmal auf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schub ist ähnelt.
        /// </summary>
        internal static string Schub_ist {
            get {
                return ResourceManager.GetString("Schub ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schubindikator leer! Standard laden? ähnelt.
        /// </summary>
        internal static string Schubindikator_Leer__Standard_Laden {
            get {
                return ResourceManager.GetString("Schubindikator_Leer__Standard_Laden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string SprachenName {
            get {
                return ResourceManager.GetString("SprachenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stelle den Regler nun auf den bremswert ähnelt.
        /// </summary>
        internal static string Stelle_den_Regler_nun_auf_den_bremswert {
            get {
                return ResourceManager.GetString("Stelle den Regler nun auf den bremswert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  und bestätige mit OK ähnelt.
        /// </summary>
        internal static string und_bestaetige_mit_OK {
            get {
                return ResourceManager.GetString("und bestaetige mit OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und soll ähnelt.
        /// </summary>
        internal static string und_soll {
            get {
                return ResourceManager.GetString("und soll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wechsel innerhalb von 7 Sekunden zum TSW und warte ähnelt.
        /// </summary>
        internal static string Wechsel_innerhalb_von_7_Sekunden_zum_TSW_und_warte {
            get {
                return ResourceManager.GetString("Wechsel_innerhalb_von_7_Sekunden_zum_TSW_und_warte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du wirklich &quot; ähnelt.
        /// </summary>
        internal static string Willst_du_wirklich {
            get {
                return ResourceManager.GetString("Willst_du_wirklich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugauswahl ähnelt.
        /// </summary>
        internal static string Zugauswahl {
            get {
                return ResourceManager.GetString("Zugauswahl", resourceCulture);
            }
        }
    }
}
